import 'package:flutter/material.dart';
import 'package:nsg_input/country/nsg_input_country_item.dart';
import 'package:nsg_input/nsg_input.dart';

class NsgInputCountry extends NsgInput {
  NsgInputCountry(
      {ValueChanged<NsgInputCountryItem> onChanged,
      ValueChanged<NsgInputCountryItem> onInit,
      NsgInputCountryItem initialSelection,
      List<NsgInputCountryItem> elements = const [],
      List<NsgInputCountryItem> favorite = const [],
      TextStyle textStyle,
      EdgeInsetsGeometry padding = const EdgeInsets.all(0.0),
      bool showPictureOnly = false,
      InputDecoration searchDecoration = const InputDecoration(),
      TextStyle searchStyle,
      TextStyle dialogTextStyle,
      WidgetBuilder emptySearchBuilder,
      Function(NsgInputCountryItem) builder,
      bool enabled = true,
      TextOverflow textOverflow = TextOverflow.ellipsis,
      Size dialogSize,
      List<NsgInputCountryItem> objectsFilter,
      bool alignLeft = false,
      bool showPicture = true,
      bool hideMainText = false,
      bool showPictureMain,
      bool showPictureDialog,
      double pictureWidth = 32.0,
      bool hideSearch = false,
      Key key})
      : super(
            onChanged: onChanged,
            onInit: onInit,
            initialSelection: initialSelection,
            elements: elements,
            favorite: favorite,
            textStyle: textStyle,
            padding: padding,
            showPictureOnly: showPictureOnly,
            searchDecoration: searchDecoration,
            searchStyle: searchStyle,
            dialogTextStyle: dialogTextStyle,
            emptySearchBuilder: emptySearchBuilder,
            alignLeft: alignLeft,
            showPicture: showPicture,
            showPictureDialog: showPictureDialog,
            hideMainText: hideMainText,
            showPictureMain: showPictureMain,
            builder: builder,
            pictureWidth: pictureWidth = 32.0,
            enabled: enabled = true,
            textOverflow: textOverflow,
            //comparator,
            objectsFilter: objectsFilter,
            hideSearch: hideSearch,
            dialogSize: dialogSize,
            key: key);
}
